"""Entity Resolution, Parity Scoring, and Normalization Subsystem."""

from pipeline.entity_resolution.matcher import (
    EntityMatcher,
    EntityMatchStatus,
    EntityRecord,
    EntityResolutionResult,
    FieldComparisonDetail,
    ResolutionScore,
    jaro_winkler_similarity,
    token_set_ratio,
)
from pipeline.entity_resolution.normalizer import (
    EntityNormalizer,
    NormalizedAddress,
    NormalizedOrgName,
    is_same_company,
    normalize_address,
    normalize_legal_abbreviations,
    normalize_org_name,
    normalize_punctuation,
    normalize_whitespace,
)
from pipeline.entity_resolution.validators import (
    ValidationResult,
    validate_address,
    validate_company_name,
    validate_date,
    validate_financial_value,
    validate_gstin,
    validate_pan,
    validate_udyam,
)

__all__ = [
    "EntityMatcher",
    "EntityMatchStatus",
    "EntityRecord",
    "EntityResolutionResult",
    "FieldComparisonDetail",
    "ResolutionScore",
    "jaro_winkler_similarity",
    "token_set_ratio",
    "EntityNormalizer",
    "NormalizedOrgName",
    "NormalizedAddress",
    "normalize_org_name",
    "normalize_address",
    "normalize_whitespace",
    "normalize_punctuation",
    "normalize_legal_abbreviations",
    "is_same_company",
    "ValidationResult",
    "validate_pan",
    "validate_gstin",
    "validate_udyam",
    "validate_date",
    "validate_financial_value",
    "validate_company_name",
    "validate_address",
]
